controller_list:
  - name: fake_robot_arm_controller
    joints:
      - base
      - motor1
      - motor2
      - motor3
      - motor4
      - motor5
  - name: fake_robot_gripper_controller
    joints:
      []
initial:  # Define initial robot poses.
  - group: robot_arm
    pose: home